CREATE TABLE IF NOT EXISTS arcade_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(20) NOT NULL,
  username_lower VARCHAR(20) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES arcade_users(id) ON DELETE CASCADE,
  game VARCHAR(20) NOT NULL CONSTRAINT scores_game_check CHECK (game IN ('chess', 'solitaire', 'checkers', 'rift', 'starfall', 'neonbreak', 'lumen', 'petal', 'driftline', 'pocketputt', 'fourfold', 'wispwood', 'parcel', 'keepsake', 'mosaic')),
  score INTEGER NOT NULL CHECK (score >= 0 AND score <= 100000000),
  outcome VARCHAR(32) NOT NULL,
  run_id VARCHAR(80) NOT NULL,
  played_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, run_id)
);
CREATE INDEX IF NOT EXISTS scores_user_history ON scores(user_id, played_at DESC);
CREATE INDEX IF NOT EXISTS scores_game ON scores(game, score DESC);

-- Expand the catalog for existing installations without touching recorded rounds.
ALTER TABLE scores DROP CONSTRAINT IF EXISTS scores_game_check;
ALTER TABLE scores ADD CONSTRAINT scores_game_check CHECK (game IN ('chess', 'solitaire', 'checkers', 'rift', 'starfall', 'neonbreak', 'lumen', 'petal', 'driftline', 'pocketputt', 'fourfold', 'wispwood', 'parcel', 'keepsake', 'mosaic'));
