import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

/** Remove only names generated by this test run, from its explicit development DB. */
export function cleanupAccounts(names: string[]) {
  if (!names.length || process.env.E2E_CLEANUP_DB === "false") return;
  if (names.some((name) => !/^[A-Za-z0-9_]+$/.test(name)))
    throw new Error("Unexpected test account name");
  const query = `DELETE FROM arcade_users WHERE username IN (${names.map((name) => `'${name}'`).join(",")})`;
  if (process.env.E2E_DATABASE_URL) {
    execFileSync(
      "psql",
      [process.env.E2E_DATABASE_URL, "-v", "ON_ERROR_STOP=1", "-c", query],
      { stdio: "pipe" },
    );
  } else {
    execFileSync(
      "docker",
      [
        "compose",
        "exec",
        "-T",
        "db",
        "psql",
        "-U",
        process.env.DATABASE_USER ?? "arcade",
        "-d",
        "arcade",
        "-v",
        "ON_ERROR_STOP=1",
        "-c",
        query,
      ],
      { cwd: fileURLToPath(new URL("../..", import.meta.url)), stdio: "pipe" },
    );
  }
}
